services:
  teletop:
    build: .
    restart: on-failure:3
  
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=teletop
      - MYSQL_ROOT_PASSWORD=teletop
